### ISSUE TITLE
3.b Implementation Explanation

### ISSUE THREAD

**Issue by apj520** [apj520/ENG1-Team-13-Assessment-2#10]

**Comment by apj520** [comment]
Documentation about the games implementation:
(From Assessment Brief) Explain how your code implements your architecture and requirements
(incorporating your recorded changes for Assessment 2). Briefly explain any
significant new features, e.g. non-primitive data types, significant algorithms or data
structures. Give a systematic report of any significant changes made to the previous
software, clearly justifying each change, and relating it to the requirements and
architecture by pointing to relevant class names and requirement IDs. Note that, if a
change has significant side effects, it needs a solid software engineering justification.
State explicitly any of the features required for Assessment 2 that are not (fully)
implemented. (10 marks, ≤ 4 pages)

**Comment by aymanish** [comment]
Started working on the document. Explained and justified significant changes implemented by @aymanish . Currently in progress.
Requesting @R-sc-e to do the same for their changes

**Comment by aymanish** [comment]
Worked on the systematic report of changes for 3b. Added all my changes
Waiting for @R-sc-e to add their changes as well
