### ISSUE TITLE
4.a Testing Methodology

### ISSUE THREAD

**Issue by apj520** [apj520/ENG1-Team-13-Assessment-2#11]

**Comment by apj520** [comment]
Explanation about our program testing methodology:
Briefly summarise your testing method(s) and approach(es), explaining why these are appropriate for the project. (5 marks, ≤ 1 page)

**Comment by YumisZyutyu** [comment]
02.05.22 
Overtaking for review

**Comment by YumisZyutyu** [comment]
03.05.22 
Corrections done, great writing and explanation! 
Fixed few grammar and punctuation errors.
