### ISSUE TITLE
5. b Report on the actual CI Infrastructure

### ISSUE THREAD

**Issue by YumisZyutyu** [apj520/ENG1-Team-13-Assessment-2#13]

**Comment by aymanish** [comment]
Updated 5b on the drive with justification of CI tool and describes the current infrastructure and configuration used for the current CI (updated with code quality check). Needs trimming and review @YumisZyutyu . Keep in mind this doc will be updated in parallel with the any changes made to the actual CI implementation. Moving on to review

**Comment by aymanish** [comment]
Updated CI infrastructure under implementation issue #15 
Need to update 5b documentation accordingly

**Comment by aymanish** [comment]
Updated 5b documentation with explanation of updated and additional workflows

**Comment by YumisZyutyu** [comment]
27/04/22 Comments added and grammar mistakes corrected. Awaiting for the comments to be resolved by Ayman if he thinks necessary. 
The major problem with the file is its readability, as it seems hard to read a couple of the paragraphs. Some references to the code will be useful to have to help readability.
The rest of the file is well written and nearly ready for submission.

**Comment by aymanish** [comment]
Updated 5b documentation and resolved most comments. Restructured the paragraphs to be more coherent and concise.
Awaiting review by @YumisZyutyu 
Unable to find a better way to refer to the code than just referring to them in bold. Might add line numbers but already filled up the page limit sadly.
The 2nd page of the document has justifications which will be useful for 5a assigned to Yumis
