### ISSUE TITLE
3.a Final testing environment (with gdxtestrunner)

### ISSUE THREAD

**Issue by R-sc-e** [apj520/ENG1-Team-13-Assessment-2#16]
Trying to set up the testing environment with gdxtestrunner. It is expected there will be issues with rendering.

**Comment by R-sc-e** [comment]
Sadly, I couldn't get the testing to work. The expected issue that Katie was mentioning keeps occurring. I tried solving it with and without mockito but seems to be above my abilities. My suggestion is to just try and do as much testing as possible, refactoring all their code will be a nightmare frankly.

**Comment by aymanish** [comment]
Do u mean even the unit tests or the integration tests?

**Comment by aymanish** [comment]
@Streuss added final tests
