### ISSUE TITLE
2.a. Formal Approach

### ISSUE THREAD

**Issue by YumisZyutyu** [apj520/ENG1-Team-13-Assessment-2#2]

**Comment by westie1138** [comment]
# 04/03/22 - 11:00
## Brandon

Document previously contained an outline of what needed to be written in the document.

All of the points have been fully written up, once this document has been reviewed, it is pretty much ready for submission, unless any changes are required.

**Comment by YumisZyutyu** [comment]
### 07/03/33 - 16:00

- I have added a few changes and have commented on anything that sounded unclear. 
- Few minor things have to be completed before moving the issue to the next stage
- [x] Add reference for agile.
- [x] Add reference for GitHub kanban and issues if any.
- [x] Go over the things I have added and check if you agree or if you have more to add.
- [ ] Could include a snapshot of the boards in the website and refer to those. 
- [x] Add the change management process of how we decided what to remove from team 3's documentation. 

- Overall the work meets most required points from the assessment, except change management of the existing documents. I.e. we review it before we correct it then put it into review again and complete it. 
- Great work from @westie1138 !

**Comment by westie1138** [comment]
## 07/03/22 - 17:10

Made changes as requested by @YumisZyutyu and added the references to the bottom.
