### ISSUE TITLE
2.b.i Requirements Changes

### ISSUE THREAD

**Issue by apj520** [apj520/ENG1-Team-13-Assessment-2#4]

**Comment by apj520** [comment]
Altered the Requirements to include new requirements for assessment 2 and removed unnecessary ones from the table.

**Comment by YumisZyutyu** [comment]
Changes on Requirements Table: [Used the walkthrough inspection methhod]

- Added the new requirements for assessment 2 and split them according to the tables created by team 3 following the same ID format team 3 had set and set them to the correct user requirements 
- Changed the priority on any pre-existent requirements that didn’t have to be implemented until assessment 2
[Still needs justification]

**Comment by westie1138** [comment]
Taking over to review and write a brief explanation justifying the changes made.

**Comment by westie1138** [comment]
## 11/03/22 - 10:55

All the various changes (and lack of) have been documented and are beginning to be written up in full.

**Comment by YumisZyutyu** [comment]
Taking over to review and feedback. 
(16/04/22)

**Comment by YumisZyutyu** [comment]
Review complete. 

- More requirements could be added as we go along, therefore the issue will remain open. 
- FR_GAME_DIFFICULTY and FR_SAVE_POINT still need justifying in the "write up" document

As a side note might be useful to split the Power-Ups requirement (UR_POWER_UPS) into the individual 5 components requested by the new brief. 

(16/04/22)

**Comment by westie1138** [comment]
## 22/04/22 - 10:30
Full write up completed, with the rest of the functional requirements being added and the lack of changes to NFRs being added too.

**Comment by YumisZyutyu** [comment]
22/04/22 - 10:40 
File reviewed and moved to the "Reviewer approved" column.
