### ISSUE TITLE
2.b.iv Risk Assessment Changes

### ISSUE THREAD

**Issue by apj520** [apj520/ENG1-Team-13-Assessment-2#5]

**Comment by apj520** [comment]
Altered risk assessment to clean it up and make it fit our assessment requirements better

**Comment by YumisZyutyu** [comment]
Taking over to write a brief explanation and justification for the changes done on the table.

**Comment by apj520** [comment]
Added risks R16 - R21, Reimplemented risk ownership and Colour coded severity levels

**Comment by YumisZyutyu** [comment]
26/04/22 22:45 

Ready to be reviewed by @westie1138. Please note I am still waiting on a few clarifications from Dimitris and Ayman, however the majority of the work is done.

**Comment by westie1138** [comment]
## 29/04/22
Review complete
