### ISSUE TITLE
5.a Continuous Integration method and approaches

### ISSUE THREAD

**Issue by YumisZyutyu** [apj520/ENG1-Team-13-Assessment-2#7]

**Comment by aymanish** [comment]
Completed the method and approaches + justification for continuous integration as a new document (version 1) in Google drive under Continuous Integration folder. Awaiting review

**Comment by aymanish** [comment]
Needs to be updated with proper referencing of justifications.
@YumisZyutyu , if doc still needs to be updated after review (as mentioned above), do we create a new issue or move this issue back to the inprogress table

**Comment by aymanish** [comment]
Updated 5a documentation by adding further justification of CI method and approach. @YumisZyutyu ask me about anything u dont understand about the new CI methods

**Comment by YumisZyutyu** [comment]
03.05.22 
File complete, waiting for @aymanish for review.
