### ISSUE TITLE
2.b.ii Abstract/Concrete Architecture Changes

### ISSUE THREAD

**Issue by apj520** [apj520/ENG1-Team-13-Assessment-2#8]

**Comment by apj520** [comment]
Changes to the architecture to accommodate for assessment 2

**Comment by westie1138** [comment]
## 11/03/22 - 10:25

Document set up, waiting on the changes for the architecture to occur so that I can begin writing up.

**Comment by westie1138** [comment]
## 29/04/22 - 11:20
All explanations and justifications written in overview format. These need to be reviewed, then I can begin writing it up properly.
